In [51]:
import trimesh
import scipy
import numpy as np
import matplotlib.cm as cm
import nibabel as nib
import gdist
import sys
#import meshlabPY
#import io_AI
import matplotlib.pyplot as plt
from IPython.display import clear_output
import time
import importlib
import pandas as pd
import os
from scipy import stats
import ast

In [10]:
sys.path.insert(1, "/Users/dvarelat/Documents/MASTER/TFM/methods")
import cardiac_region
importlib.reload(cardiac_region)
import cardiac_region as c

In [3]:
folder = "7_20190404_E2"
ESPECIMEN = folder.split("_")[1] + "_" + folder.split("_")[2]
image_path = f"/Users/dvarelat/Documents/MASTER/TFM/DATA/RESULTS/membranes/GASP_PNAS/{ESPECIMEN}_mGFP_XYZ_predictions_GASP.nii.gz"
DFFILE = f"/Users/dvarelat/Documents/MASTER/TFM/DATA/EXTRACTION/{folder}/{ESPECIMEN}_cell_properties_radiomics.csv"
#file_mesh = f"/Users/dvarelat/Documents/MASTER/TFM/midS/{ESPECIMEN}_myo_midS.ply"
file_mesh = f"/Users/dvarelat/Documents/MASTER/TFM/midS_spl/{ESPECIMEN}_spl_midS.ply"
print(ESPECIMEN)

20190404_E2


In [4]:
df = pd.read_csv(DFFILE)

In [6]:
proxy = nib.load(image_path)
img   = np.asarray(proxy.get_fdata(), dtype=proxy.get_data_dtype())
img = img.astype("uint16")
img.shape

(1024, 1024, 448)

In [11]:
dim_info = c.load3D_metadata(image_path)

In [18]:
mesh = trimesh.load_mesh(file_mesh, process=False)
final_number_faces = 10000
d = 20
mesh = mesh.simplify_quadratic_decimation(int(final_number_faces))

In [19]:
print(f"Numero de vertices {len(mesh.vertices)}")
mesh.faces.shape

Numero de vertices 5416


(10000, 3)

In [ ]:
n_points = 9601
points, faces = mesh_mid.sample(n_points, return_index=True)
normal = mesh_mid.face_normals[faces]

In [20]:
mesh.face_normals

array([[ 0.34869297, -0.93509409, -0.06334241],
       [ 0.53710192, -0.81182995, -0.22902763],
       [ 0.56493161, -0.7164287 , -0.40936804],
       ...,
       [ 0.57147637, -0.7605897 , -0.30808776],
       [ 0.63648975, -0.22667026, -0.73722547],
       [ 0.19997481,  0.40357288,  0.89282641]])

In [21]:
mesh.faces

TrackedArray([[5044, 1807, 1478],
              [4087, 1509, 1073],
              [2003, 4087, 3505],
              ...,
              [2328, 4957,  335],
              [5126, 2234, 4404],
              [1181,  992, 3931]])

In [36]:
centers_coords = [[round(i) for i in center] for center in mesh.triangles_center]
j_pix = np.floor(np.array(centers_coords) / [dim_info["x_res"], dim_info["y_res"], dim_info["z_res"]]).astype("uint16")
j_pix

array([[443, 571, 160],
       [417, 562, 131],
       [416, 565, 125],
       ...,
       [272, 499,  89],
       [908, 376,  67],
       [636, 817, 389]], dtype=uint16)

In [43]:
j_pixel_labels = img[j_pix[:, 0], j_pix[:, 1], j_pix[:, 2]] 
unique_labels = set(j_pixel_labels)
print(len(unique_labels))
len([i for i in df.original_labels if i in unique_labels])

1698


1258

In [44]:
j_pixel_labels.shape
[for c in ]

(10000,)

In [48]:
mesh.face_normals[0]

array([ 0.34869297, -0.93509409, -0.06334241])

In [49]:
mesh.face_normals

array([[ 0.34869297, -0.93509409, -0.06334241],
       [ 0.53710192, -0.81182995, -0.22902763],
       [ 0.56493161, -0.7164287 , -0.40936804],
       ...,
       [ 0.57147637, -0.7605897 , -0.30808776],
       [ 0.63648975, -0.22667026, -0.73722547],
       [ 0.19997481,  0.40357288,  0.89282641]])

In [50]:
j_pixel_labels

array([6494, 5121, 5121, ..., 2980,  829,    0], dtype=uint16)

In [55]:
dict_vectors = dict(zip(df.original_labels, [ast.literal_eval(i) for i in df.eigenvectors]))

In [57]:
dict_vectors[5121]

[[0.098, -0.005, 0.995], [0.526, 0.849, -0.048], [-0.845, 0.528, 0.085]]